sudo: false
language: node_js
node_js:
  - '5.0'
  - '4.0'
  - '0.12'
  - '0.10'
services:
  - memcached
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
